### ISSUE TITLE
Support Binary Ninja

### ISSUE THREAD

**Issue by XVilka** [seemoo-lab/polypyus#2]
[Binary Ninja](https://binary.ninja/) is a popular reverse engineering platform for static and dynamic binary analysis, disassembly, decompilation (WIP, almost done), rich [system of extensions](https://github.com/Vector35/binaryninja-api) and plugins. It would amazing to support it in the program too. Especially it will be helpful to coordinate work in teams, where different members prefer different reversing instruments.

![image](https://user-images.githubusercontent.com/203261/80333754-b3fbbe00-8881-11ea-904f-b829a134f794.png)

**Comment by jiska2342** [comment]
In our disassembler benchmarks, *Binary Ninja* performed even better than *IDA* without *Thumbs Up* scripts. So this one will definitely be a priority issue after everything with *IDA* is stable :)

**Comment by jiska2342** [comment]
Added basic support for Binary Ninja. Tested with Binary Ninja 2 and Python 3.7.5 on Ubuntu to import all CYW20735 symbols.
![image](https://user-images.githubusercontent.com/7442426/85959510-1fa2fa00-b99d-11ea-978a-a6d26a6e08b1.png)
