### ISSUE TITLE
Inconsistent delimiter for polypyus csv files

### ISSUE THREAD

**Issue by mariusmue** [seemoo-lab/polypyus#7]
Hi all!
I'm just writing a small Ghidra importer exporter for the csv format, and I realized that the csv format is currently not well defined.

In most of the script, the csv delimiter is set to `delimiter=" "`, however, some of the csv files you provide as example do not follow this format, e.g.: https://github.com/seemoo-lab/polypyus/blob/master/firmware/history/20739-polypyus-export.csv

For the ghidra importer/exporter, which delimiter should I assume?

**Comment by FreebeJan** [comment]
the correct one is the space delimiter. Please feel free to fix the inconsisten csv files

**Comment by FreebeJan** [comment]
> the correct one is the space delimiter. Please feel free to fix the inconsisten csv files

I just pushed to master a fix for the inconsistency
